version: '3.7'

services:
  nodebbx:
    image: vimagick/nodebb
    ports:
      - "4580:4580"
    volumes:
      - ./data:/var/lib/nodebb
      - /usr/src/nodebb/build
      - /usr/src/nodebb/node_modules
      - /usr/src/nodebb/public/uploads
    restart: always

  mongo:
    image: "mongo:latest"
    command: mongod --port 28018
    ports:
      - "28018:28018"
    volumes:
      - /data/mongodb/db:/data/db
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nodebb.conf:/etc/nginx/conf.d/nodebb.conf
    ports:
      - 80:8080
    links:
      - nodebbx
    restart: always
